In [29]:
import pandas as pd

In [2]:
clean_permit = pd.read_pickle('clean/permit.pickle')
clean_violation = pd.read_pickle('clean/violation.pickle') 
clean_crime = pd.read_pickle('clean/crime.pickle')
clean_311 = pd.read_pickle('clean/311.pickle')
def cut_date(df):
    return df[df.date.map(lambda x: x.year)>=2005]
clean_permit, clean_violation, clean_crime, clean_311 = map(cut_date,[clean_permit, clean_violation, clean_crime, clean_311])

In [3]:
# thanks to Linghao Zhang zlhdnc1994@gmail.com
import string
import re

def clean_addr(s):
    s = s.lower()
    s = s.translate(string.maketrans('', ''), string.punctuation)
    s = re.sub(r'\bstreet\b', r'st', s)
    s = re.sub(r'\broad\b', r'rd', s)
    s = re.sub(r'\bavenue\b', r'av', s)
    s = re.sub(r'\bdrive\b', r'dr', s)
    s = re.sub(r'\bboulevard\b', r'bd', s)
    s = re.sub(r'\bblvd\b', r'bd', s)
    s = re.sub(r'\bnorth\b', r'n', s)
    s = re.sub(r'\bsouth\b', r's', s)
    s = re.sub(r'\bwest\b', r'w', s)
    s = re.sub(r'\beast\b', r'e', s)
    s = re.sub(r' +', r' ', s)
    p = s.find('detroit mi')
    if p != -1:
        s = s[:p]
    p = s.find('detroitmi')
    if p != -1:
        s = s[:p]        
    s = s.strip()
    return s

In [4]:
clean_violation.addr = clean_violation.addr.map(clean_addr)
clean_permit.addr = clean_permit.addr.map(clean_addr)

In [5]:
clean_permit.groupby(['addr','lat','lng']).count()

                                      date
addr               lat      lng
100 river place    0.414722 0.717940     1
100 w alexandrine  0.489254 0.602173     1
1000 14th          0.343842 0.574507     2
1000 baldwin       0.498920 0.765084     1
1000 s dix         0.165460 0.341316     1
1000 scotten       0.311348 0.524149     3
10000 mettetal     0.586461 0.217391     1
10002 nottingham   0.807875 0.888000     1
10005 somerset     0.811995 0.892747     1
10006 forrer       0.587179 0.230130     1
1001 e mcnichols   0.838619 0.516114     1
10010 quincy       0.616480 0.430983     1
10011 mettetal     0.586965 0.217192     1
10012 woodmont     0.587132 0.210965     1
10016 beaconsfield 0.808754 0.885189     2
10019 meyers       0.586150 0.317268     1
10021 montrose     0.588307 0.233197     1
10026 greensboro   0.805305 0.880623     1
10027 forrer       0.588717 0.229934     1
10028 pinehurst    0.586648 0.324234     1
10030 meyers       0.593946 0.317728     1
10034 greensboro   0.805815 0.880809     1
10036 stahelin     0.586870 0.165790     1
10038 iris         0.592848 0.312707     1
10039 mettetal     0.589073 0.217140     1
10039 st marys     0.827183 0.441563     1
1005 melbourne     0.644547 0.586585     1
10050 aurora       0.601123 0.339998     1
10059 balfour      0.818637 0.898800     2
10076 nottingham   0.812203 0.889673     1
...                                    ...
9919 sorrento      0.584235 0.307786     1
9920 cheyenne      0.583736 0.301411     1
9920 ohio          0.589191 0.354670     1
9928 schaefer      0.584680 0.291809     1
993 e savannah     0.877976 0.518102     1
9930 woodmont      0.581154 0.211072     1
9932 meyers        0.587517 0.317835     1
9933 mckinney      0.823119 0.903895     1
9935 sorrento      0.585369 0.307758     1
9941 mckinney      0.823535 0.904054     1
9944 appoline      0.586770 0.314484     1
9944 meyers        0.588304 0.317822     1
9952 meyers        0.588829 0.317813     1
9953 archdale      0.582121 0.191366     1
9970 belleterre    0.594451 0.401245     1
9972 memorial      0.583938 0.201199     1
9973 schaefer      0.583236 0.291249     1
9980 memorial      0.584448 0.201171     1
9981 archdale      0.584080 0.191338     1
9986 asbury park   0.585327 0.213993     1
9986 woodside      0.595015 0.398095     2
9987 gratiot       0.714006 0.751082     2
9987 montrose      0.585832 0.233225     1
9988 meyers        0.591191 0.317774     1
9988 st marys      0.827183 0.441563     1
9989 manor         0.591501 0.320604     1
9994 meyers        0.591584 0.317767     1
9995 mettetal      0.585986 0.217220     1
9995 rutherford    0.586295 0.226881     1
9999 gratiot ave   0.714816 0.751384     2

[5266 rows x 1 columns]

In [6]:
clean_permit.drop('date',axis=1).groupby(['addr']).apply(lambda g: len(g.apply(lambda g: (g['lat'],g['lng']),axis=1).unique()))
_[_!=1]

                                      date
addr               lat      lng
100 river place    0.414722 0.717940   NaN
100 w alexandrine  0.489254 0.602173   NaN
1000 14th          0.343842 0.574507   2.0
1000 baldwin       0.498920 0.765084   NaN
1000 s dix         0.165460 0.341316   NaN
1000 scotten       0.311348 0.524149   3.0
10000 mettetal     0.586461 0.217391   NaN
10002 nottingham   0.807875 0.888000   NaN
10005 somerset     0.811995 0.892747   NaN
10006 forrer       0.587179 0.230130   NaN
1001 e mcnichols   0.838619 0.516114   NaN
10010 quincy       0.616480 0.430983   NaN
10011 mettetal     0.586965 0.217192   NaN
10012 woodmont     0.587132 0.210965   NaN
10016 beaconsfield 0.808754 0.885189   2.0
10019 meyers       0.586150 0.317268   NaN
10021 montrose     0.588307 0.233197   NaN
10026 greensboro   0.805305 0.880623   NaN
10027 forrer       0.588717 0.229934   NaN
10028 pinehurst    0.586648 0.324234   NaN
10030 meyers       0.593946 0.317728   NaN
10034 greensboro   0.805815 0.880809   NaN
10036 stahelin     0.586870 0.165790   NaN
10038 iris         0.592848 0.312707   NaN
10039 mettetal     0.589073 0.217140   NaN
10039 st marys     0.827183 0.441563   NaN
1005 melbourne     0.644547 0.586585   NaN
10050 aurora       0.601123 0.339998   NaN
10059 balfour      0.818637 0.898800   2.0
10076 nottingham   0.812203 0.889673   NaN
...                                    ...
9919 sorrento      0.584235 0.307786   NaN
9920 cheyenne      0.583736 0.301411   NaN
9920 ohio          0.589191 0.354670   NaN
9928 schaefer      0.584680 0.291809   NaN
993 e savannah     0.877976 0.518102   NaN
9930 woodmont      0.581154 0.211072   NaN
9932 meyers        0.587517 0.317835   NaN
9933 mckinney      0.823119 0.903895   NaN
9935 sorrento      0.585369 0.307758   NaN
9941 mckinney      0.823535 0.904054   NaN
9944 appoline      0.586770 0.314484   NaN
9944 meyers        0.588304 0.317822   NaN
9952 meyers        0.588829 0.317813   NaN
9953 archdale      0.582121 0.191366   NaN
9970 belleterre    0.594451 0.401245   NaN
9972 memorial      0.583938 0.201199   NaN
9973 schaefer      0.583236 0.291249   NaN
9980 memorial      0.584448 0.201171   NaN
9981 archdale      0.584080 0.191338   NaN
9986 asbury park   0.585327 0.213993   NaN
9986 woodside      0.595015 0.398095   2.0
9987 gratiot       0.714006 0.751082   2.0
9987 montrose      0.585832 0.233225   NaN
9988 meyers        0.591191 0.317774   NaN
9988 st marys      0.827183 0.441563   NaN
9989 manor         0.591501 0.320604   NaN
9994 meyers        0.591584 0.317767   NaN
9995 mettetal      0.585986 0.217220   NaN
9995 rutherford    0.586295 0.226881   NaN
9999 gratiot ave   0.714816 0.751384   2.0

[5266 rows x 1 columns]

In [7]:
idx = clean_permit[clean_permit.addr=='3716 benson'].index
clean_permit.loc[idx,'lat'] = 0.529960
clean_permit.loc[idx,'lng'] = 0.709746

In [8]:
idx = clean_permit[clean_permit.addr=='4893 grayton'].index
clean_permit.loc[idx,'lat'] = 0.767547
clean_permit.loc[idx,'lng'] = 0.945206

In [9]:
clean_permit

           lat       lng       date                   addr
0     0.714869  0.903169 2015-08-28            4331 barham
1     0.720103  0.750076 2015-08-28         9707 bessemore
2     0.761821  0.905622 2015-08-28         5315 berkshire
3     0.985508  0.903681 2015-08-28      16670 bringard dr
4     0.111348  0.371944 2015-08-28          1454 beatrice
5     0.747155  0.904098 2015-08-28           5035 balfour
6     0.757334  0.900653 2015-08-28           5297 balfour
7     0.758097  0.900395 2015-08-28           5315 balfour
8     0.756953  0.900783 2015-08-28           5280 balfour
9     0.575037  0.935626 2015-08-28            427 ashland
10    0.751425  0.876294 2015-08-28             5576 alter
11    0.037499  0.351530 2015-08-28           3109 bassett
12    0.580173  0.933882 2015-08-28            471 ashland
13    0.779074  0.899830 2015-08-28         5807 berkshire
14    0.552256  0.891211 2015-08-28          478 algonquin
15    0.529960  0.709746 2015-08-28            3716 benson
16    0.118746  0.371976 2015-08-28         1334 annabelle
18    0.715338  0.863752 2015-08-27         13934 e warren
19    0.390874  0.483954 2015-08-27          4503 michigan
20    0.722329  0.873743 2015-08-27         14436 e warren
21    0.797481  0.778411 2015-08-27        11793 glenfield
23    0.641524  0.910097 2015-08-27        14725 kercheval
24    0.534235  0.246273 2015-08-25          8846 whitcomb
25    0.530181  0.256614 2015-08-24              14944 joy
26    0.683912  0.170054 2015-08-24        14015 greenview
27    0.850477  0.813518 2015-08-24  13982 houstonwhittier
28    0.716358  0.240083 2015-08-24            14511 prest
29    0.627254  0.498165 2015-08-24     9138 rosa parks bd
30    0.721051  0.358614 2015-08-24            8340 lyndon
31    0.502305  0.173390 2015-08-21         8256 greenview
...        ...       ...        ...                    ...
7100  0.836891  0.714181 2006-02-10         8300 nuernberg
7101  0.841919  0.714120 2006-02-10        13807 french rd
7102  0.841919  0.714120 2006-02-10        13807 french rd
7103  0.911408  0.846337 2006-02-10        14875 faircrest
7104  0.911408  0.846337 2006-02-10        14875 faircrest
7105  0.705428  0.481926 2006-02-10          1555 highland
7106  0.531444  0.375030 2010-05-27           8610 central
7107  0.674892  0.528351 2010-05-26        630 w boston bd
7108  0.582893  0.417580 2010-05-26          9526 yosemite
7109  0.891700  0.135609 2010-05-26     18982 westmoreland
7110  0.692226  0.123665 2010-05-26            14178 stout
7111  0.873239  0.507406 2010-05-26           651 e nevada
7112  0.754850  0.364933 2010-05-26         8120 ellsworth
7113  0.907188  0.485192 2010-05-26        130 w brentwood
7114  0.901370  0.644566 2010-05-26           18621 albany
7115  0.484329  0.403569 2010-05-26          6382 majestic
7116  0.638280  0.590152 2010-05-25           8210 cameron
7117  0.038651  0.319723 2010-05-25       25901 w outer dr
7118  0.568777  0.806808 2010-05-24           2210 hurlbut
7119  0.484329  0.403569 2010-05-24          6382 majestic
7120  0.523252  0.496399 2010-05-24            6209 lawton
7121  0.562544  0.389671 2010-05-20            9339 monica
7122  0.780563  0.409206 2010-05-20         15727 muirland
7123  0.785887  0.414473 2010-05-20         15798 parkside
7124  0.787567  0.414250 2010-05-20         15823 parkside
7125  0.688700  0.443758 2010-05-20            2646 leslie
7126  0.705594  0.466771 2010-05-20            1958 leslie
7127  0.569258  0.386787 2010-05-20          9436 burnette
7128  0.709097  0.472001 2010-05-20            1678 leslie
7129  0.780978  0.409206 2010-05-20         15733 muirland

[5879 rows x 4 columns]

In [10]:
len(clean_permit.addr.unique())

5264

In [11]:
clean_violation.groupby(['addr','lat','lng']).count()

                                    date  JudgeAmt
addr             lat      lng
0 10th           0.589581 0.189353    69        69
0 10th st        0.361170 0.593306     1         1
0 11th           0.807036 0.319381     3         3
0 15th           0.957655 0.180793     1         1
0 18th           0.443943 0.530613     1         1
0 21st           0.352293 0.547032     1         1
0 22nd           0.386842 0.529169     1         1
0 30th st        0.445454 0.460365     1         1
0 31st st        0.423561 0.464350     1         1
0 32nd           0.423805 0.460666     1         1
0 32nd st        0.423805 0.460666     2         2
0 33rd st        0.423637 0.457705     1         1
0 35th           0.415428 0.454786     3         3
0 52nd           0.497553 0.633330     4         4
0 aaron          0.574337 0.680096    12        12
0 aaron st       0.574337 0.680096     1         1
0 abbott         0.365713 0.590037     7         7
0 abington       0.655523 0.202946     1         1
0 acacia         0.696835 0.069153     4         4
0 ackley         0.676030 0.667689     4         4
0 adair          0.440212 0.726911     9         9
0 adams ave      0.415320 0.622536     1         1
0 atlanta        0.735015 0.770870     1         1
0 bacon          0.215692 0.455510     1         1
0 balmoral dr    0.919892 0.436784     1         1
0 benson         0.528461 0.707375     1         1
0 bryden         0.554934 0.378256     1         1
0 cabot          0.370308 0.371543     1         1
0 chicago        0.616817 0.459508     1         1
0 chippewa       0.944236 0.050011     1         1
...                                  ...       ...
9999 bacon       0.215692 0.455510     1         1
9999 covert      0.849190 0.679374     1         1
9999 dacosta     0.468563 0.079419     5         5
9999 eagle       0.490045 0.395486     1         1
9999 faircrest   0.911525 0.850181     1         1
9999 gratiot     0.714816 0.751384     2         2
9999 hackett     0.735660 0.222195     2         2
9999 hill        0.831335 0.440781     1         1
9999 jackson     0.405260 0.474777     3         3
9999 kaline dr   0.402208 0.583251     1         1
9999 la salle bd 0.816367 0.430217     2         2
9999 longacre    0.585570 0.194684     1         1
9999 m l king bd 0.414233 0.519974     1         1
9999 mack        0.608016 0.786525     1         1
9999 parker      0.644800 0.724822     1         1
9999 salem       0.850848 0.006022     1         1
9999 seminole    0.666463 0.723383     1         1
9999 yacama      0.948764 0.505620     2         2
99997 adair      0.440212 0.726911     1         1
99998 adair      0.440212 0.726911     1         1
99999 10th       0.589581 0.189353     1         1
99999 14th       0.905640 0.180111     1         1
99999 15th       0.957655 0.180793     1         1
99999 18th       0.443943 0.530613     1         1
99999 35th       0.415428 0.454786     1         1
99999 acacia     0.696835 0.069153     1         1
99999 adair      0.440212 0.726911     1         1
99999 bacon      0.215692 0.455510     1         1
99999 dacosta    0.468563 0.079419     2         2
99999 first      0.391733 0.620023     1         1

[93427 rows x 2 columns]

In [26]:
buildings = pd.concat([clean_permit[['addr','lat','lng']],clean_violation[['addr','lat','lng']]]).drop_duplicates("addr",keep="first").reset_index().drop('index',axis=1)

In [28]:
buildings.to_csv('clean/buildings.csv')

In [25]:
98674

98674

In [ ]:
buildings